# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alper's Blog
email: alperyilmaz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Experiences and thougths of a commandline enthusiast on Linux, bioinformatics..
  I am also intested in finding better ways to teach..
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alperyilmaz.org" # the base hostname & protocol for your site
twitter_username: alperyilmaz
github_username:  alperyilmaz

# Build settings
markdown: kramdown

# Do not copy these files to the output directory
exclude: ["deploy","README.md"]

